name: Release
on:
  push:
    branches:
      - main
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Setup build environment
        run: sudo apt-get install -y bash gawk zip
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Build package
        run: bash build.sh
        working-directory: ${{ github.workspace }}
      - name: Archive artifacts
        uses: actions/upload-artifact@v3
        with:
          name: orderable-org-plugin
          path: orderable-org-*.zip
